### ISSUE TITLE
docker compose

### ISSUE THREAD

**Issue by Solear** [oskarkraemer/komootHeatmap#2]
Hi, I love this tool. I can finally see at a glance where I have already been and where there are still “gaps”. 
I would love it if the tool was also available as a docker-compose for my selfhostetd-compose landscape. I'm too stupid to create something like that myself :-(

Thank you for the great work!

**Comment by elmicha** [comment]
You could use this as a start:
```
services:
  komoot-heatmap:
    command:
      - "flask"
      - "run"
      - "--host=0.0.0.0"
      - "--port=80"
    image: "komoot-heatmap:latest"
    ports:
      - "1827:80/tcp"
    restart: unless-stopped
```
This will listen on port 1827, if you want to change it, change the 1827 of course.

I created the compose file with docker-autocompose:

    docker run --rm -v /var/run/docker.sock:/var/run/docker.sock \
       ghcr.io/red5d/docker-autocompose 058bae3c5335

where 058bae3c5335 is the container id of the running container.

**Comment by Solear** [comment]
Thank you, elmicha!
I've tried this, but I have to download the image manually.
It is because this repo is not available at docker hub itself?

dockeg:
`Error response from daemon: pull access denied for komoot-heatmap, repository does not exist or may require 'docker login': denied: requested access to the resource is denied`

**Comment by elmicha** [comment]
Yes, the image is not at docker hub. You can add "build:" to the compose.yaml file:

```
services:
  komoot-heatmap:
    build:
      dockerfile: Dockerfile
    command:
      - "flask"
      - "run"
      - "--host=0.0.0.0"
      - "--port=80"
    image: "komoot-heatmap:latest"
    ports:
      - "1827:80/tcp"
    restart: unless-stopped
```
Then you can build it with `docker compose build`.

**Comment by Solear** [comment]
Thank you again, elmicha. Is there a reason why this image is not at the docker hub?

**Comment by macphil** [comment]
Or use this repo directly as build context as follows:

```yaml
services:
  komoot-heatmap:
    build:
      context: https://github.com/oskarkraemer/komootHeatmap.git
    container_name: komoot-heatmap
    ports:
      - 9080:80
    restart: unless-stopped
```
